import type { MdxIndustry } from "./types";

export interface IndustryAttribute {
  key: string;
  label: string;
  kind: "text" | "number" | "boolean" | "list";
}

export interface IndustryStorefrontConfig {
  industry: MdxIndustry;
  label: string;
  templateName: string;
  tone: string;
  primaryAction: string;
  itemNoun: string;
  itemPlural: string;
  ownSectionTitle: string;
  partnerSectionTitle: string;
  attributeTitle: string;
  modules: string[];
  sections: string[];
  categories: string[];
  attributes: IndustryAttribute[];
  accentClass: string;
  softClass: string;
  darkClass: string;
}

const COMMON_MARKETPLACE_MODULES = ["Marketplace", "Offers & Deals", "CRM", "Reports"];
const PRODUCT_MODULES = ["Marketplace", "Inventory", "Offers & Deals", "Delivery Tracking", "Affiliate", "Reports"];
const BOOKING_MODULES = ["Marketplace", "Calendar / Booking", "Offers & Deals", "CRM", "Staff & Tasks", "Reports"];

export const industryStorefrontConfigs: Record<MdxIndustry, IndustryStorefrontConfig> = {
  Hotel: {
    industry: "Hotel",
    label: "Hotel / Resort",
    templateName: "Hotel Experience Marketplace",
    tone: "Room-first storefront for rooms, packages, dining, wellness, and local experiences.",
    primaryAction: "Check availability",
    itemNoun: "room",
    itemPlural: "rooms and packages",
    ownSectionTitle: "Rooms and hotel packages",
    partnerSectionTitle: "Partner guest experiences",
    attributeTitle: "Stay details",
    modules: ["Marketplace", "Calendar / Booking", "Hotel Management", "Offers & Deals", "CRM", "Delivery Tracking", "Reports"],
    sections: ["Hero booking", "Rooms", "Packages", "Dining", "Spa & Wellness", "Local Experiences"],
    categories: ["Rooms", "Packages", "Dining", "Wellness", "Transport"],
    attributes: [
      { key: "roomType", label: "Room type", kind: "text" },
      { key: "maxGuests", label: "Max guests", kind: "number" },
      { key: "beds", label: "Beds", kind: "text" },
      { key: "amenities", label: "Amenities", kind: "list" },
      { key: "breakfastIncluded", label: "Breakfast", kind: "boolean" },
    ],
    accentClass: "bg-blue-600",
    softClass: "bg-blue-50 text-blue-700 ring-blue-100",
    darkClass: "text-blue-700",
  },
  Restaurant: {
    industry: "Restaurant",
    label: "Restaurant / Cafe",
    templateName: "Restaurant Deals",
    tone: "Menu-first storefront for ordering, combos, table booking, and delivery.",
    primaryAction: "Order now",
    itemNoun: "menu item",
    itemPlural: "menu items",
    ownSectionTitle: "Menu and combos",
    partnerSectionTitle: "Partner add-ons",
    attributeTitle: "Food details",
    modules: ["Marketplace", "Restaurant Management", "Offers & Deals", "Inventory", "Delivery Tracking", "Reports"],
    sections: ["Food hero", "Popular combos", "Today deals", "Family meals", "Table booking", "Delivery"],
    categories: ["Mains", "Snacks", "Beverages", "Family Meals", "Desserts"],
    attributes: [
      { key: "prepTime", label: "Prep time", kind: "text" },
      { key: "spiceLevel", label: "Spice", kind: "text" },
      { key: "diet", label: "Diet", kind: "text" },
      { key: "serves", label: "Serves", kind: "number" },
    ],
    accentClass: "bg-orange-600",
    softClass: "bg-orange-50 text-orange-700 ring-orange-100",
    darkClass: "text-orange-700",
  },
  "Trekking / Travel": {
    industry: "Trekking / Travel",
    label: "Trekking / Travel",
    templateName: "Travel Experience",
    tone: "Package-first storefront for trips, guides, transport, and travel gear partners.",
    primaryAction: "Book trip",
    itemNoun: "trip",
    itemPlural: "trips",
    ownSectionTitle: "Trips and guide services",
    partnerSectionTitle: "Partner gear and stays",
    attributeTitle: "Trip details",
    modules: ["Marketplace", "Calendar / Booking", "Offers & Deals", "CRM", "Affiliate", "Reports"],
    sections: ["Trip hero", "Day trips", "Multi-day packages", "Guides", "Gear", "Hotel partners"],
    categories: ["Day Trips", "Treks", "Guides", "Transport", "Gear"],
    attributes: [
      { key: "duration", label: "Duration", kind: "text" },
      { key: "difficulty", label: "Difficulty", kind: "text" },
      { key: "groupSize", label: "Group size", kind: "text" },
      { key: "includes", label: "Includes", kind: "list" },
    ],
    accentClass: "bg-emerald-600",
    softClass: "bg-emerald-50 text-emerald-700 ring-emerald-100",
    darkClass: "text-emerald-700",
  },
  "Salon / Spa": {
    industry: "Salon / Spa",
    label: "Salon / Spa",
    templateName: "Salon / Spa Booking",
    tone: "Appointment-first storefront for services, stylists, packages, and beauty offers.",
    primaryAction: "Book appointment",
    itemNoun: "service",
    itemPlural: "services",
    ownSectionTitle: "Services and packages",
    partnerSectionTitle: "Partner style offers",
    attributeTitle: "Appointment details",
    modules: BOOKING_MODULES,
    sections: ["Beauty hero", "Book services", "Spa offers", "Bridal packages", "Stylists", "Partner fashion"],
    categories: ["Hair", "Spa", "Makeup", "Nails", "Bridal"],
    attributes: [
      { key: "duration", label: "Duration", kind: "text" },
      { key: "staff", label: "Specialist", kind: "text" },
      { key: "gender", label: "For", kind: "text" },
      { key: "addOns", label: "Add-ons", kind: "list" },
    ],
    accentClass: "bg-pink-600",
    softClass: "bg-pink-50 text-pink-700 ring-pink-100",
    darkClass: "text-pink-700",
  },
  Clothing: {
    industry: "Clothing",
    label: "Clothing / Fashion",
    templateName: "Fashion Retail Drop",
    tone: "Visual product storefront for sizes, colors, stock, collections, and flash offers.",
    primaryAction: "Add to bag",
    itemNoun: "style",
    itemPlural: "styles",
    ownSectionTitle: "Featured clothing",
    partnerSectionTitle: "Partner lifestyle offers",
    attributeTitle: "Style details",
    modules: PRODUCT_MODULES,
    sections: ["Fashion hero", "New arrivals", "Size-aware catalogue", "Flash sale", "Bundles", "Partner services"],
    categories: ["Jackets", "Shoes", "Trekking Wear", "Accessories", "Formal"],
    attributes: [
      { key: "sizes", label: "Sizes", kind: "list" },
      { key: "colors", label: "Colors", kind: "list" },
      { key: "material", label: "Material", kind: "text" },
      { key: "fit", label: "Fit", kind: "text" },
      { key: "season", label: "Season", kind: "text" },
      { key: "returnPolicy", label: "Returns", kind: "text" },
    ],
    accentClass: "bg-slate-900",
    softClass: "bg-slate-100 text-slate-700 ring-slate-200",
    darkClass: "text-slate-900",
  },
  Grocery: {
    industry: "Grocery",
    label: "Grocery / Supermarket",
    templateName: "Fresh Grocery Market",
    tone: "Fast-moving grocery storefront for units, freshness, expiry, stock, and delivery slots.",
    primaryAction: "Add grocery",
    itemNoun: "grocery item",
    itemPlural: "grocery items",
    ownSectionTitle: "Fresh groceries",
    partnerSectionTitle: "Partner household offers",
    attributeTitle: "Grocery details",
    modules: PRODUCT_MODULES,
    sections: ["Fresh hero", "Daily essentials", "Produce", "Bulk staples", "Delivery slots", "Staff deals"],
    categories: ["Produce", "Dairy", "Staples", "Household", "Snacks", "Beverages"],
    attributes: [
      { key: "unit", label: "Unit", kind: "text" },
      { key: "weight", label: "Weight", kind: "text" },
      { key: "origin", label: "Origin", kind: "text" },
      { key: "freshness", label: "Freshness", kind: "text" },
      { key: "expiryDate", label: "Expiry", kind: "text" },
      { key: "organic", label: "Organic", kind: "boolean" },
      { key: "deliveryWindow", label: "Delivery", kind: "text" },
    ],
    accentClass: "bg-emerald-600",
    softClass: "bg-emerald-50 text-emerald-700 ring-emerald-100",
    darkClass: "text-emerald-700",
  },
  Events: {
    industry: "Events",
    label: "Events / Venue",
    templateName: "Event Offers",
    tone: "Ticketing storefront for event listings, registrations, capacity, and partner food offers.",
    primaryAction: "Buy ticket",
    itemNoun: "event",
    itemPlural: "events",
    ownSectionTitle: "Events and tickets",
    partnerSectionTitle: "Partner event add-ons",
    attributeTitle: "Event details",
    modules: ["Marketplace", "Calendar / Booking", "Offers & Deals", "CRM", "Reports"],
    sections: ["Event hero", "Upcoming events", "Tickets", "Food partners", "Sponsors", "Reviews"],
    categories: ["Music", "Dining", "Workshop", "Community", "Nightlife"],
    attributes: [
      { key: "date", label: "Date", kind: "text" },
      { key: "time", label: "Time", kind: "text" },
      { key: "capacity", label: "Capacity", kind: "text" },
      { key: "venue", label: "Venue", kind: "text" },
    ],
    accentClass: "bg-amber-500",
    softClass: "bg-amber-50 text-amber-700 ring-amber-100",
    darkClass: "text-amber-700",
  },
  "Local Services": {
    industry: "Local Services",
    label: "Local Services",
    templateName: "Local Service Booking",
    tone: "Quote and booking storefront for transport, repairs, delivery, and service providers.",
    primaryAction: "Request quote",
    itemNoun: "service",
    itemPlural: "services",
    ownSectionTitle: "Services",
    partnerSectionTitle: "Partner services",
    attributeTitle: "Service details",
    modules: BOOKING_MODULES,
    sections: ["Service hero", "Quote request", "Service packages", "Availability", "Reviews", "Partners"],
    categories: ["Transport", "Repairs", "Delivery", "Home Services", "Business Services"],
    attributes: [
      { key: "serviceArea", label: "Service area", kind: "text" },
      { key: "responseTime", label: "Response", kind: "text" },
      { key: "availability", label: "Availability", kind: "text" },
      { key: "included", label: "Included", kind: "list" },
    ],
    accentClass: "bg-teal-600",
    softClass: "bg-teal-50 text-teal-700 ring-teal-100",
    darkClass: "text-teal-700",
  },
  "CCTV & Security": {
    industry: "CCTV & Security",
    label: "CCTV & Security",
    templateName: "Security Services",
    tone: "Trust-first service storefront for installation, monitoring, audits, and AMC contracts.",
    primaryAction: "Request security quote",
    itemNoun: "package",
    itemPlural: "packages",
    ownSectionTitle: "Security packages",
    partnerSectionTitle: "Partner maintenance offers",
    attributeTitle: "Security details",
    modules: ["Marketplace", "Calendar / Booking", "Offers & Deals", "CRM", "Automation", "Reports"],
    sections: ["Trust hero", "Packages", "AMC contracts", "Monitoring", "Audit", "Quote request"],
    categories: ["CCTV", "Alarm", "Access Control", "Monitoring", "AMC"],
    attributes: [
      { key: "cameraCount", label: "Cameras", kind: "number" },
      { key: "monitoring", label: "Monitoring", kind: "text" },
      { key: "warranty", label: "Warranty", kind: "text" },
      { key: "amc", label: "AMC", kind: "boolean" },
    ],
    accentClass: "bg-slate-800",
    softClass: "bg-slate-100 text-slate-700 ring-slate-200",
    darkClass: "text-slate-800",
  },
  "IT Services": {
    industry: "IT Services",
    label: "IT Services",
    templateName: "IT Support Services",
    tone: "Service storefront for IT support, networking, AMC plans, and emergency response.",
    primaryAction: "Request IT support",
    itemNoun: "service",
    itemPlural: "services",
    ownSectionTitle: "IT services",
    partnerSectionTitle: "Partner business services",
    attributeTitle: "IT details",
    modules: ["Marketplace", "Calendar / Booking", "Offers & Deals", "CRM", "Automation", "Reports"],
    sections: ["Support hero", "AMC plans", "Remote support", "Networking", "Device repair", "Quote request"],
    categories: ["AMC", "Networking", "Repair", "Cloud", "Security"],
    attributes: [
      { key: "sla", label: "SLA", kind: "text" },
      { key: "remoteSupport", label: "Remote", kind: "boolean" },
      { key: "devices", label: "Devices", kind: "number" },
      { key: "coverage", label: "Coverage", kind: "text" },
    ],
    accentClass: "bg-indigo-600",
    softClass: "bg-indigo-50 text-indigo-700 ring-indigo-100",
    darkClass: "text-indigo-700",
  },
  Cleaning: {
    industry: "Cleaning",
    label: "Cleaning Services",
    templateName: "Cleaning Services",
    tone: "Service storefront for cleaning packages, recurring plans, hygiene certificates, and quotes.",
    primaryAction: "Book cleaning",
    itemNoun: "cleaning service",
    itemPlural: "cleaning services",
    ownSectionTitle: "Cleaning services",
    partnerSectionTitle: "Partner property services",
    attributeTitle: "Cleaning details",
    modules: BOOKING_MODULES,
    sections: ["Clean hero", "Service packages", "Recurring plans", "Certificates", "Team", "Quote request"],
    categories: ["Home", "Office", "Hotel", "Kitchen", "Deep Clean", "AMC"],
    attributes: [
      { key: "areaSize", label: "Area size", kind: "text" },
      { key: "frequency", label: "Frequency", kind: "text" },
      { key: "teamSize", label: "Team", kind: "number" },
      { key: "suppliesIncluded", label: "Supplies", kind: "boolean" },
      { key: "certificate", label: "Certificate", kind: "text" },
    ],
    accentClass: "bg-teal-600",
    softClass: "bg-teal-50 text-teal-700 ring-teal-100",
    darkClass: "text-teal-700",
  },
  "General Retail": {
    industry: "General Retail",
    label: "General Retail",
    templateName: "Retail Marketplace",
    tone: "Flexible product storefront for stock, offers, partner listings, and delivery.",
    primaryAction: "Add to cart",
    itemNoun: "product",
    itemPlural: "products",
    ownSectionTitle: "Products",
    partnerSectionTitle: "Partner products",
    attributeTitle: "Product details",
    modules: PRODUCT_MODULES,
    sections: ["Retail hero", "Products", "Deals", "Bundles", "Delivery", "Partners"],
    categories: ["Products", "Accessories", "Bundles", "Services", "Deals"],
    attributes: [
      { key: "sku", label: "SKU", kind: "text" },
      { key: "brand", label: "Brand", kind: "text" },
      { key: "stock", label: "Stock", kind: "number" },
      { key: "warranty", label: "Warranty", kind: "text" },
    ],
    accentClass: "bg-blue-600",
    softClass: "bg-blue-50 text-blue-700 ring-blue-100",
    darkClass: "text-blue-700",
  },
  "Wellness / Supplements": {
    industry: "Wellness / Supplements",
    label: "Wellness & Supplements",
    templateName: "Wellness & Health Store",
    tone: "Clean, transparent product storefront for supplements, vitamins, and health products with full Swedish compliance.",
    primaryAction: "Beställ nu",
    itemNoun: "produkt",
    itemPlural: "produkter",
    ownSectionTitle: "Våra produkter",
    partnerSectionTitle: "Partner hälsoprodukter",
    attributeTitle: "Produktdetaljer",
    modules: ["Marketplace", "Inventory", "Offers & Deals", "Subscription Orders", "Delivery Tracking", "Affiliate", "Reports"],
    sections: ["Brand hero", "Certifications", "Goal filter", "Products", "Ingredients", "Subscriptions", "Trust"],
    categories: ["Vitaminer", "Mineraler", "Protein", "Omega", "Örter & Adaptogener", "Bundles", "Skönhet"],
    attributes: [
      { key: "goals",          label: "Hälsomål",        kind: "list"    },
      { key: "form",           label: "Form",             kind: "text"    },
      { key: "certifications", label: "Certifieringar",   kind: "list"    },
      { key: "dietaryFlags",   label: "Kost",             kind: "list"    },
      { key: "ingredients",    label: "Ingredienser",     kind: "text"    },
      { key: "dosage",         label: "Dosering",         kind: "text"    },
      { key: "servings",       label: "Portioner",        kind: "number"  },
      { key: "weight",         label: "Innehåll",         kind: "text"    },
    ],
    accentClass: "bg-emerald-700",
    softClass: "bg-emerald-50 text-emerald-800 ring-emerald-100",
    darkClass: "text-emerald-800",
  },
  "Fika / Coffee": {
    industry: "Fika / Coffee",
    label: "Fika & Coffee",
    templateName: "Fika & Coffee Shop",
    tone: "Warm, artisan café storefront for pastries, coffee, preorder slots and loyalty stamp cards.",
    primaryAction: "Beställ nu",
    itemNoun: "produkt",
    itemPlural: "bakverk & drycker",
    ownSectionTitle: "Dagens bakverk & drycker",
    partnerSectionTitle: "Partner kafé-erbjudanden",
    attributeTitle: "Produktdetaljer",
    modules: ["Marketplace", "Inventory", "Offers & Deals", "Loyalty Cards", "Preorder Slots", "Delivery Tracking", "Reports"],
    sections: ["Kafé hero", "Stamkort", "Förbeställ", "Bakverk", "Kaffe & dryck", "Säsongsspecial", "Erbjudanden"],
    categories: ["Kanelbullar", "Kardemummabullar", "Tårtor & Bakverk", "Smörgåsar", "Kaffe", "Te & Dryck", "Säsongsspecial"],
    attributes: [
      { key: "allergens",     label: "Allergener",       kind: "list"    },
      { key: "dietary",       label: "Kost",             kind: "list"    },
      { key: "freshBaked",    label: "Nybakat",          kind: "boolean" },
      { key: "preorderOnly",  label: "Endast förbeställ",kind: "boolean" },
      { key: "availableDays", label: "Tillgängliga dagar",kind: "list"   },
      { key: "season",        label: "Säsong",           kind: "text"    },
      { key: "servings",      label: "Antal bitar",      kind: "number"  },
    ],
    accentClass: "bg-amber-700",
    softClass: "bg-amber-50 text-amber-900 ring-amber-100",
    darkClass: "text-amber-900",
  },

  "Craft Beer / Brewery": {
    industry: "Craft Beer / Brewery",
    label: "Craft Beer & Brewery",
    templateName: "Craft Beer Taproom",
    tone: "Artisan brewery storefront for craft beers, tasting sessions, Beer Club subscriptions, and taproom bookings.",
    primaryAction: "Order beer",
    itemNoun: "beer",
    itemPlural: "beers",
    ownSectionTitle: "Our craft beers",
    partnerSectionTitle: "Guest taps & partner brews",
    attributeTitle: "Beer details",
    modules: ["Marketplace", "Inventory", "Subscription Orders", "Calendar / Booking", "Offers & Deals", "Delivery Tracking", "Reports"],
    sections: ["Taproom hero", "Beer catalogue", "ABV/style filter", "Beer Club", "Taproom booking", "Tasting events"],
    categories: ["IPA", "Pale Ale", "Stout & Porter", "Lager", "Sour & Wild", "Seasonal", "Merchandise"],
    attributes: [
      { key: "abv",         label: "ABV %",          kind: "number"  },
      { key: "ibu",         label: "IBU",             kind: "number"  },
      { key: "malts",       label: "Malts",           kind: "text"    },
      { key: "hops",        label: "Hops",            kind: "text"    },
      { key: "yeast",       label: "Yeast",           kind: "text"    },
      { key: "servingTemp", label: "Serving temp",    kind: "text"    },
      { key: "glassware",   label: "Glassware",       kind: "text"    },
      { key: "foodPairing", label: "Food pairing",    kind: "text"    },
      { key: "organic",     label: "Organic",         kind: "boolean" },
      { key: "vegan",       label: "Vegan",           kind: "boolean" },
    ],
    accentClass: "bg-amber-900",
    softClass: "bg-amber-50 text-amber-900 ring-amber-100",
    darkClass: "text-amber-900",
  },

  "Natural Beauty / Skincare": {
    industry: "Natural Beauty / Skincare",
    label: "Natural Beauty & Skincare",
    templateName: "Natural Beauty Store",
    tone: "Clean-beauty storefront for skincare, hair care, and body care — EU-certified, cruelty free, INCI transparent.",
    primaryAction: "Lägg i varukorg",
    itemNoun: "produkt",
    itemPlural: "produkter",
    ownSectionTitle: "Våra skönhetsprodukter",
    partnerSectionTitle: "Partner skönhetserbjudanden",
    attributeTitle: "Produktdetaljer",
    modules: ["Marketplace", "Inventory", "Offers & Deals", "Subscription Orders", "Delivery Tracking", "Affiliate", "Reports"],
    sections: ["Brand hero", "Certifications", "Skin type filter", "Products", "INCI list", "Subscriptions", "Trust"],
    categories: ["Ansiktsvård", "Kroppsvård", "Hårvård", "Solskydd", "Makeup", "Parfym & Doft", "Ögonvård"],
    attributes: [
      { key: "skinTypes",     label: "Hudtyp",             kind: "list"   },
      { key: "skinConcerns",  label: "Hudproblem",         kind: "list"   },
      { key: "certifications",label: "Certifieringar",     kind: "list"   },
      { key: "freeFrom",      label: "Fri från",           kind: "list"   },
      { key: "ingredients",   label: "Ingredienser (INCI)",kind: "text"   },
      { key: "howToUse",      label: "Användning",         kind: "text"   },
      { key: "size",          label: "Storlek",            kind: "text"   },
      { key: "skincareLine",  label: "Produktserie",       kind: "text"   },
    ],
    accentClass: "bg-rose-600",
    softClass: "bg-rose-50 text-rose-800 ring-rose-100",
    darkClass: "text-rose-800",
  },

  "Supplier / Wholesale": {
    industry: "Supplier / Wholesale",
    label: "Supplier / Wholesale",
    templateName: "B2B Wholesale Catalogue",
    tone: "B2B catalogue storefront for bulk orders, retailer pricing, MOQ, and wholesale invoicing.",
    primaryAction: "Place wholesale order",
    itemNoun: "product",
    itemPlural: "products",
    ownSectionTitle: "Wholesale catalogue",
    partnerSectionTitle: "Partner supplier listings",
    attributeTitle: "Product & pricing details",
    modules: ["Marketplace", "Inventory", "Wholesale Orders", "Retailer Management", "Delivery Tracking", "Invoicing", "Reports"],
    sections: ["Catalogue hero", "Product catalogue", "Bulk pricing", "MOQ & pricing tiers", "Retailer area", "Delivery & logistics"],
    categories: ["Raw Materials", "Packaged Goods", "FMCG", "Equipment", "Chemicals", "Textiles"],
    attributes: [
      { key: "moq", label: "Min. order qty", kind: "number" },
      { key: "unit", label: "Unit", kind: "text" },
      { key: "bulkPrice", label: "Bulk price / unit", kind: "text" },
      { key: "leadTime", label: "Lead time", kind: "text" },
      { key: "origin", label: "Origin", kind: "text" },
      { key: "certification", label: "Certification", kind: "text" },
    ],
    accentClass: "bg-amber-600",
    softClass: "bg-amber-50 text-amber-700 ring-amber-100",
    darkClass: "text-amber-700",
  },
};

export const industryOptions = Object.values(industryStorefrontConfigs);

export function getIndustryStorefrontConfig(industry: MdxIndustry) {
  return industryStorefrontConfigs[industry] ?? industryStorefrontConfigs["General Retail"];
}

export function formatAttributeValue(value: string | number | boolean | string[]) {
  if (Array.isArray(value)) return value.join(", ");
  if (typeof value === "boolean") return value ? "Yes" : "No";
  return String(value);
}
